"""add segment traffic observations

Revision ID: fb63001da0f8
Revises: ea20ee9c238b
Create Date: 2026-09-03 05:33:47.299365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb63001da0f8'
down_revision: Union[str, Sequence[str], None] = 'ea20ee9c238b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment_traffic_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=False),
    sa.Column('from_stop_id', sa.Integer(), nullable=False),
    sa.Column('to_stop_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('travel_time_minutes', sa.Float(), nullable=False),
    sa.Column('average_speed_kmh', sa.Float(), nullable=False),
    sa.Column('traffic_condition', sa.String(length=30), nullable=False),
    sa.Column('traffic_duration_seconds', sa.Float(), nullable=False),
    sa.Column('static_duration_seconds', sa.Float(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_stop_id'], ['corridor_stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_stop_id'], ['corridor_stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment_traffic_observations')
    # ### end Alembic commands ###
